# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/KATracking/AppicAdSpecs'
source 'https://github.com/CocoaPods/Specs.git'
target 'KATrackingAdDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KATrackingAdDemo
   pod 'AppicAdSDK'
   pod 'GDTMobSDK'
#   pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug'] #必选
#   pod 'DoraemonKit/WithGPS', '~> 3.0.4', :configurations => ['Debug'] #可选
#   pod 'DoraemonKit/WithLoad', '~> 3.0.4', :configurations => ['Debug'] #可选
#   pod 'DoraemonKit/WithLogger', '~> 3.0.4', :configurations => ['Debug'] #可选
#   pod 'DoraemonKit/WithDatabase', '~> 3.0.4', :configurations => ['Debug'] #可选
#   pod 'DoraemonKit/WithMLeaksFinder', '~> 3.0.4', :configurations => ['Debug'] #可选
#   pod 'DoraemonKit/WithWeex', '~> 3.0.4', :configurations => ['Debug'] #可选
end

